name: Build TTS App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
    
    - name: 设置 Python 环境
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5==5.15.9
        pip install edge-tts
        pip install lameenc
        pip install pyinstaller
    
    - name: 编译 EXE
      run: |
        pyinstaller --onefile --windowed --name="文字转语音工具" --hidden-import=edge_tts --hidden-import=lameenc --hidden-import=asyncio --hidden-import=PyQt5.QtCore --hidden-import=PyQt5.QtGui --hidden-import=PyQt5.QtWidgets --hidden-import=PyQt5.QtMultimedia --clean tts_app.py
    
    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: TTS-Tool-Windows
        path: dist/文字转语音工具.exe
        retention-days: 30
    
    - name: 创建 Release (如果是 tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: dist/文字转语音工具.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
