name: Build Windows EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyqt5 pyttsx3 lameenc pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --windowed tts_app.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: TTSApp-Windows
        path: dist/tts_app.exe
