name: Build EXE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyqt5 pyttsx3 lameenc pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --noconsole --onefile tts.py

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TTSApp-exe
          path: dist/your_script.exe
