name: Build EXE

on:
  workflow_dispatch:   # 手动触发

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pyinstaller pyqt5 edge-tts lameenc

    - name: Build exe
      run: |
        pyinstaller --onefile --noconsole --hidden-import lameenc --hidden-import PyQt5.sip tts.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: exe-build
        path: dist/*.exe

